run:
  go: v1.22

linters:
  disable-all: true
  enable:
    - errcheck
    - gci
    - gofmt
    - goimports
    - govet
    - gosimple
    - ineffassign
    - misspell
    - perfsprint
    - prealloc
    - staticcheck
    - unconvert
    - unused
    - whitespace
