name: continuous deployment

on:
  workflow_dispatch:

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: build project
        run: GOARCH=arm64 go build -o dist/build_binary
      - name: copy build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'dist/build_binary,migrations'
          target: 'container'
