name: continuous integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

# required for PR annotations
permissions:
  contents: read
  checks: write

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: check linting
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: unit testing
        run: go test ./... --v
